### ISSUE TITLE
feature: loading text next to the spinner

### ISSUE THREAD

**Issue by omBratteng** [slsfi/digital_edition_web#74]
Could improve the UX a little bit, in case someone doesn't understand the that the three dots mean something is loading.

It could then be, `Loading ···`. Localised of course
Perhaps temporarily set the cursor to `cursor: progress;`, either on the whole page, or just in that part of the page, as another visual feedback that something is happening.

**Comment by SebastianKohler** [comment]
The three dots spinner has been replaced by a crescent spinner, widely used in web apps. Should be easy to understand.
